### ISSUE TITLE
infografía 

### ISSUE THREAD

**Issue by DanAlejandr** [SistemasTecTlaxiaco/infografia-DanAlejandr#2]
[infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-DanAlejandr/files/12501803/infografia.pdf)

**Comment by 23620031** [comment]
REDACCIÓN Y ORTOGRAFÍA 10/10
EXPOSICIÓN DE IDEAS CENTRALES 13/15 (Sintesis regular de la información encontrada)
ORGANIZACIÓN DE LA INFORMACIÓN 15/15
USO DE IMÁGENES Y COLORES 15/15
PRESENTACIÓN VISUAL 15/15
REFERENCIAS 15/15
PRESENTACIÓN 15/15

CALIFICADO POR EL EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
